import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#425c85",
        "primary-dim": "#365079",
        "primary-container": "#b3cdfd",
        "primary-fixed": "#b3cdfd",
        "primary-fixed-dim": "#a5bfee",
        "on-primary": "#eff2ff",
        "on-primary-container": "#2a446c",
        "on-primary-fixed": "#133057",
        "on-primary-fixed-variant": "#334d76",
        "secondary": "#575c60",
        "secondary-dim": "#4b5054",
        "secondary-container": "#dfe3e7",
        "secondary-fixed": "#dfe3e7",
        "secondary-fixed-dim": "#d1d5d9",
        "on-secondary": "#eff3f7",
        "on-secondary-container": "#4d5256",
        "on-secondary-fixed": "#3b4043",
        "on-secondary-fixed-variant": "#575c60",
        "tertiary": "#b31a35",
        "tertiary-dim": "#a2052b",
        "tertiary-container": "#ff9196",
        "tertiary-fixed": "#ff9196",
        "tertiary-fixed-dim": "#ff7982",
        "on-tertiary": "#ffefee",
        "on-tertiary-container": "#680017",
        "on-tertiary-fixed": "#390009",
        "on-tertiary-fixed-variant": "#79001d",
        "error": "#b31b25",
        "error-dim": "#9f0519",
        "error-container": "#fb5151",
        "on-error": "#ffefee",
        "on-error-container": "#570008",
        "success": "#16a34a",
        "success-container": "#dcfce7",
        "on-success": "#ffffff",
        "surface": "#f6f5ff",
        "surface-bright": "#f6f5ff",
        "surface-dim": "#c7d3ff",
        "surface-variant": "#d3dcff",
        "surface-tint": "#425c85",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eef0ff",
        "surface-container": "#e2e7ff",
        "surface-container-high": "#dbe1ff",
        "surface-container-highest": "#d3dcff",
        "on-surface": "#202d51",
        "on-surface-variant": "#4e5a81",
        "on-background": "#202d51",
        "background": "#f6f5ff",
        "outline": "#69769e",
        "outline-variant": "#9facd7",
        "inverse-surface": "#000b2d",
        "inverse-on-surface": "#8f9cc6",
        "inverse-primary": "#b3cdfd",
        "brand-navy": "#1A365D",
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
